### PR TITLE
Use `Accept-Language` if language is not in the url

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Thanks @lucacasonato for the idea!

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
Love that you wrote a custom accept-language parser :P

**Comment by nicolo-ribaudo** [comment]
I tried looking on https://deno.land/x?query=accept-language but I couldn't find anything, maybe one day I'll extract it to a standalone package!

**Comment by nicolo-ribaudo** [comment]
Whops, https://deno.land/x/negotiator@1.0.1/src/language.ts?code

**Comment by lucacasonato** [comment]
I didn't want to taint you with this link before you had done the implementation, but here is how I wrote it last time: https://github.com/lucacasonato/freshworkshop/blob/main/routes/_middleware.ts.
I just used `accept-language-parser` from NPM via https://esm.sh/accept-language-parser@1.5.0.

**Pull request merged**
